export const JOIN = 'JOIN';
export const CONNECTION_SUCCESS_TTT = 'CONNECTION_SUCCESS_TTT';
export const CONNECTION_SUCCESS_DB = 'CONNECTION_SUCCESS_DB';
export const ERROR = 'ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DISPLAY_MESSAGE = 'DISPLAY_MESSAGE';

export const TTTBOX_CLICKED = 'TTTBOX_CLICKED';
